"""GameSpecification Pydantic Schema.

Defines the contract payload generated by the AI Engine and consumed by the Game Engine.
"""

from typing import List, Optional, Literal
from pydantic import BaseModel, Field, model_validator


class NarrativePayload(BaseModel):
    zone_theme: str = Field(..., description="Visual/narrative theme, e.g. cyber_core, crystal_archives")
    mission_intro: str = Field(..., description="Introductory story context for the player")


class NPCPayload(BaseModel):
    npc_id: str = Field(..., description="Unique NPC identifier, e.g. grand_scribe_alan")
    npc_name: str = Field(..., description="Display name for the NPC")
    dialogue: List[str] = Field(..., min_length=1, description="List of dialogue lines/paragraphs")
    lore_snippet: Optional[str] = Field(None, description="Optional lore or flavor text")


class ChallengeOption(BaseModel):
    id: str = Field(..., description="Option key, e.g. A, B, C, D")
    text: str = Field(..., min_length=1, description="Option display text")


class ProgressiveHint(BaseModel):
    level: int = Field(..., ge=1, le=3, description="Hint tier (1=nudge, 2=guidance, 3=scaffold)")
    type: Literal["nudge", "guidance", "scaffold"] = Field(..., description="Pedagogical hint category")
    text: str = Field(..., min_length=1, description="Hint message")


class ChallengePayload(BaseModel):
    challenge_id: str = Field(..., description="Unique challenge identifier")
    challenge_type: Literal["mcq", "concept_puzzle", "boss_override", "calculation"] = Field(
        default="mcq", description="Category of challenge interaction"
    )
    prompt: str = Field(..., min_length=5, description="The question or task prompt")
    options: List[ChallengeOption] = Field(..., min_length=2, max_length=6, description="Multiple choice options")
    correct_option_id: str = Field(..., description="ID matching the correct option")
    hints: List[ProgressiveHint] = Field(default_factory=list, description="Progressive scaffolding hints")
    explanation: str = Field(..., min_length=5, description="Pedagogical explanation of the correct answer")

    @model_validator(mode="after")
    def validate_correct_option_exists(self) -> "ChallengePayload":
        option_ids = {opt.id for opt in self.options}
        if self.correct_option_id not in option_ids:
            raise ValueError(
                f"correct_option_id '{self.correct_option_id}' does not match any available option id: {option_ids}"
            )
        return self


class BossPayload(BaseModel):
    is_boss_mission: bool = Field(default=False, description="Flag indicating if this mission includes a boss fight")
    boss_id: Optional[str] = Field(None, description="Unique boss ID if applicable")
    boss_name: Optional[str] = Field(None, description="Boss display name")
    shield_weakness_concept: Optional[str] = Field(None, description="Concept key that unlocks/damages boss shield")
    phases: int = Field(default=1, ge=1, le=5, description="Number of boss encounter phases")


class RewardPayload(BaseModel):
    xp: int = Field(default=100, ge=0, description="Experience points awarded on completion")
    knowledge_coins: int = Field(default=20, ge=0, description="In-game knowledge currency awarded")
    mastery_boost_potential: float = Field(
        default=0.1, ge=0.0, le=1.0, description="Anticipated mastery increment potential"
    )


class SpecificationMetadata(BaseModel):
    source_document_id: Optional[str] = Field(None, description="Document ID from which content was sourced")
    chunk_ids: List[str] = Field(default_factory=list, description="RAG chunk IDs used for grounding")
    generated_at: str = Field(..., description="ISO 8601 generation timestamp")
    generator_model: str = Field(..., description="AI model used for generation, e.g. gemini-2.5-flash")


class GameSpecification(BaseModel):
    version: str = Field(default="1.0.0", description="Schema version")
    mission_id: str = Field(..., min_length=1, description="Unique mission identifier, e.g. OS-CPU-001")
    concept_id: str = Field(..., min_length=1, description="Target educational concept key")
    title: str = Field(..., min_length=1, description="Mission title")
    difficulty: int = Field(..., ge=1, le=5, description="Curriculum difficulty from 1 (Very Easy) to 5 (Very Hard)")
    learning_objective: str = Field(..., min_length=5, description="Target educational objective")
    narrative: NarrativePayload = Field(..., description="Story and zone atmosphere")
    npc: NPCPayload = Field(..., description="NPC dialogue and instruction")
    challenge: ChallengePayload = Field(..., description="Interactive challenge details")
    boss: BossPayload = Field(default_factory=BossPayload, description="Boss battle specifications")
    reward: RewardPayload = Field(default_factory=RewardPayload, description="Reward economics")
    metadata: SpecificationMetadata = Field(..., description="Grounding and traceability metadata")
