"""Learning Graph and Planner schemas."""

from typing import Any, Dict, List, Optional
from pydantic import Field
from .base import ArcanaBaseModel, generate_id
from .knowledge import Concept, RelationshipType


class LearningGraphNode(ArcanaBaseModel):
    """A node in the ARCANA Learning Graph representing an educational milestone."""

    concept_id: str
    name: str
    difficulty: int = Field(default=1, ge=1, le=5)
    importance: float = Field(default=0.5, ge=0.0, le=1.0)
    prerequisite_ids: List[str] = Field(default_factory=list)
    dependent_ids: List[str] = Field(default_factory=list)
    depth: int = Field(default=0, description="Topological depth in the DAG")
    tier: int = Field(default=1, description="Learning tier or chapter group")


class LearningGraphEdge(ArcanaBaseModel):
    """A directed edge in the Learning Graph representing a dependency or flow."""

    source_id: str
    target_id: str
    relationship_type: RelationshipType
    confidence: float = 1.0


class LearningGraph(ArcanaBaseModel):
    """The directed acyclic reasoning graph powering ARCANA progression."""

    graph_id: str = Field(default_factory=lambda: generate_id("lg"))
    subject: str = Field(default="Educational Subject")
    nodes: Dict[str, LearningGraphNode] = Field(default_factory=dict)
    edges: List[LearningGraphEdge] = Field(default_factory=list)
    root_concepts: List[str] = Field(default_factory=list, description="Entry-level concepts with no prerequisites")
    terminal_concepts: List[str] = Field(default_factory=list, description="Mastery capstone concepts")
    topological_order: List[str] = Field(default_factory=list, description="Valid sequential learning order")
    is_acyclic: bool = Field(default=True)


class LearningSequence(ArcanaBaseModel):
    """The pedagogical sequence generated by the Learning Planner for a learner."""

    sequence_id: str = Field(default_factory=lambda: generate_id("seq"))
    ordered_concept_ids: List[str] = Field(default_factory=list, description="Recommended learning path")
    revision_concept_ids: List[str] = Field(default_factory=list, description="Weak concepts requiring reinforcement")
    advanced_concept_ids: List[str] = Field(default_factory=list, description="Concepts unlocked for high performers")
    deferred_concept_ids: List[str] = Field(default_factory=list, description="Concepts blocked by unmet prerequisites")
